development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: s535504
  password: jhgf201

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: s535504
  password: jhgf201