development:
  address: "smtp.gmail.com"
  port: 587
  domain: 'localhost:3000'
  user_name: 's5355049@gmail.com'
  password: 'gundam00'
  authentication: 'plain'
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: 'localhost:3000'
  user_name: 's5355049@gmail.com'
  password: 'gundam00'
  authentication: 'plain'
  enable_starttls_auto: true