development:
  :address              => "smtp.gmail.com"
  :port                 => 587
  :domain               => 'gmail.com'
  :user_name            => 's5355049@gmail.com'
  :password             => 'gundam00'
  :authentication       => 'plain'
  :enable_starttls_auto => true
productions:
  :address              => "smtp.gmail.com"
  :port                 => 587
  :domain               => 'gmail.com'
  :user_name            => 's5355049@gmail.com'
  :password             => 'gundam00'
  :authentication       => 'plain'
  :enable_starttls_auto => true